### ISSUE TITLE
JIRA enchanted into error after config database

### ISSUE THREAD

**Issue by duudo** [haxqer/jira#1]
Hi, 

When I run docker-compose to start JIRA, it can start successfully.
After I config database and click next, it didn't continue and the log shows exception.

My env as follows:
docker version : 19.03.2
docker-compose version: 1.24.1
OS: centos 7.6.1810

Thanks in advance!

log exception------------------------
jira-srv | 	java.lang.Throwable
jira-srv | 		at java.lang.Thread.sleep(Native Method)
jira-srv | 		at com.atlassian.plugin.util.WaitUntil.invoke(WaitUntil.java:79)
jira-srv | 		at com.atlassian.plugin.manager.PluginEnabler.actualEnable(PluginEnabler.java:139)
jira-srv | 		at com.atlassian.plugin.manager.PluginEnabler.enable(PluginEnabler.java:97)
jira-srv | 		at com.atlassian.plugin.manager.DefaultPluginManager.lambda$enableDependentPlugins$22(DefaultPluginManager.java:1246)
jira-srv | 		at com.atlassian.plugin.manager.DefaultPluginManager$$Lambda$278/1262772278.run(Unknown Source)
jira-srv | 		at com.atlassian.plugin.manager.PluginTransactionContext.wrap(PluginTransactionContext.java:63)
jira-srv | 		at com.atlassian.plugin.manager.DefaultPluginManager.enableDependentPlugins(DefaultPluginManager.java:1230)
jira-srv | 		at com.atlassian.plugin.manager.DefaultPluginManager.lambda$addPlugins$20(DefaultPluginManager.java:1215)
jira-srv | 		at com.atlassian.plugin.manager.DefaultPluginManager$$Lambda$273/1993176984.run(Unknown Source)
jira-srv | 		at com.atlassian.plugin.manager.PluginTransactionContext.wrap(PluginTransactionContext.java:63)
jira-srv | 		at com.atlassian.plugin.manager.DefaultPluginManager.addPlugins(DefaultPluginManager.java:1115)
jira-srv | 		at com.atlassian.jira.plugin.JiraPluginManager.addPlugins(JiraPluginManager.java:157)
jira-srv | 		at com.atlassian.plugin.manager.DefaultPluginManager.lambda$earlyStartup$3(DefaultPluginManager.java:588)
jira-srv | 		at com.atlassian.plugin.manager.DefaultPluginManager$$Lambda$165/1743911624.run(Unknown Source)
jira-srv | 		at com.atlassian.plugin.manager.PluginTransactionContext.wrap(PluginTransactionContext.java:63)
jira-srv | 		at com.atlassian.plugin.manager.DefaultPluginManager.earlyStartup(DefaultPluginManager.java:523)
jira-srv | 		at com.atlassian.jira.plugin.JiraPluginManager.earlyStartup(JiraPluginManager.java:119)
jira-srv | 		at com.atlassian.jira.component.pico.ComponentManager$PluginSystem.earlyStartup(ComponentManager.java:669)
jira-srv | 		at com.atlassian.jira.component.pico.ComponentManager.earlyStartPluginSystem(ComponentManager.java:238)
jira-srv | 		at com.atlassian.jira.upgrade.PluginSystemLauncher.start(PluginSystemLauncher.java:45)
jira-srv | 		at com.atlassian.jira.startup.DefaultJiraLauncher.lambda$postDbLaunch$2(DefaultJiraLauncher.java:145)
jira-srv | 		at com.atlassian.jira.startup.DefaultJiraLauncher$$Lambda$337/1152636331.run(Unknown Source)
jira-srv | 		at com.atlassian.jira.config.database.DatabaseConfigurationManagerImpl.runPostDbSetupRunnables(DatabaseConfigurationManagerImpl.java:283)
jira-srv | 		at com.atlassian.jira.config.database.DatabaseConfigurationManagerImpl.activateDatabase(DatabaseConfigurationManagerImpl.java:276)
jira-srv | 		at com.atlassian.jira.config.database.DatabaseConfigurationManagerImpl.activateDatabase(DatabaseConfigurationManagerImpl.java:240)
jira-srv | 		at com.atlassian.jira.web.action.setup.SetupDatabase.doExecute(SetupDatabase.java:217)
jira-srv | 		at webwork.action.ActionSupport.execute(ActionSupport.java:165)
jira-srv | 		at com.atlassian.jira.action.JiraActionSupport.execute(JiraActionSupport.java:63)
jira-srv | 		at webwork.interceptor.DefaultInterceptorChain.proceed(DefaultInterceptorChain.java:39)
jira-srv | 		at webwork.interceptor.NestedInterceptorChain.proceed(NestedInterceptorChain.java:31)
jira-srv | 		at webwork.interceptor.ChainedInterceptor.intercept(ChainedInterceptor.java:16)
jira-srv | 		at webwork.interceptor.DefaultInterceptorChain.proceed(DefaultInterceptorChain.java:35)
jira-srv | 		at webwork.dispatcher.GenericDispatcher.executeAction(GenericDispatcher.java:225)
jira-srv | 		at webwork.dispatcher.GenericDispatcher.executeAction(GenericDispatcher.java:154)
jira-srv | 		at com.atlassian.jira.web.dispatcher.JiraWebworkActionDispatcher.service(JiraWebworkActionDispatcher.java:138)
jira-srv | 		at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.jira.web.filters.JiraLastFilter.lambda$doFilter$0(JiraLastFilter.java:39)
jira-srv | 		at com.atlassian.jira.web.filters.JiraLastFilter$$Lambda$365/1934918956.doFilter(Unknown Source)
jira-srv | 		at com.atlassian.jira.web.filters.steps.ChainedFilterStepRunner.doFilter(ChainedFilterStepRunner.java:74)
jira-srv | 		at com.atlassian.jira.web.filters.JiraLastFilter.doFilter(JiraLastFilter.java:36)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.core.filters.HeaderSanitisingFilter.doFilter(HeaderSanitisingFilter.java:37)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:39)
jira-srv | 		at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:55)
jira-srv | 		at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:43)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.jira.web.filters.MobileAppRequestFilter.doFilter(MobileAppRequestFilter.java:36)
jira-srv | 		at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.jira.web.filters.accesslog.AccessLogFilter.executeRequest(AccessLogFilter.java:93)
jira-srv | 		at com.atlassian.jira.web.filters.accesslog.AccessLogFilter.doFilter(AccessLogFilter.java:79)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.jira.security.xsrf.XsrfTokenAdditionRequestFilter.doFilter(XsrfTokenAdditionRequestFilter.java:46)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:181)
jira-srv | 		at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:85)
jira-srv | 		at com.atlassian.jira.web.filters.SitemeshPageFilter.doFilter(SitemeshPageFilter.java:112)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.jira.web.filters.pagebuilder.PageBuilderFilter.doFilter(PageBuilderFilter.java:81)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.jira.web.filters.CommittedResponseHtmlErrorRecoveryFilter.doFilter(CommittedResponseHtmlErrorRecoveryFilter.java:55)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:39)
jira-srv | 		at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:55)
jira-srv | 		at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:43)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.jira.web.filters.MauEventFilter.doFilter(MauEventFilter.java:49)
jira-srv | 		at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.jira.security.JiraSecurityFilter.lambda$doFilter$0(JiraSecurityFilter.java:66)
jira-srv | 		at com.atlassian.jira.security.JiraSecurityFilter$$Lambda$359/1399394958.doFilter(Unknown Source)
jira-srv | 		at com.atlassian.seraph.filter.SecurityFilter.doFilter(SecurityFilter.java:242)
jira-srv | 		at com.atlassian.jira.security.JiraSecurityFilter.doFilter(JiraSecurityFilter.java:64)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.seraph.filter.BaseLoginFilter.doFilter(BaseLoginFilter.java:148)
jira-srv | 		at com.atlassian.jira.web.filters.JiraLoginFilter.doFilter(JiraLoginFilter.java:77)
jira-srv | 		at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:39)
jira-srv | 		at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:55)
jira-srv | 		at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:43)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.util.profiling.filters.RequestProfilingFilter.doFilter(RequestProfilingFilter.java:62)
jira-srv | 		at com.atlassian.jira.web.filters.JIRAProfilingFilter.doFilter(JIRAProfilingFilter.java:21)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.jira.web.filters.johnson.JiraJohnson503Filter.doFilter(JiraJohnson503Filter.java:79)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.jira.web.filters.johnson.JiraJohnsonFilter.doFilter(JiraJohnsonFilter.java:72)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
jira-srv | 		at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
jira-srv | 		at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
jira-srv | 		at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.jira.servermetrics.CorrelationIdPopulatorFilter.doFilter(CorrelationIdPopulatorFilter.java:30)
jira-srv | 		at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:39)
jira-srv | 		at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:55)
jira-srv | 		at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:43)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.jira.web.filters.steps.ChainedFilterStepRunner.doFilter(ChainedFilterStepRunner.java:74)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.core.filters.cache.AbstractCachingFilter.doFilter(AbstractCachingFilter.java:31)
jira-srv | 		at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.core.filters.encoding.AbstractEncodingFilter.doFilter(AbstractEncodingFilter.java:39)
jira-srv | 		at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
jira-srv | 		at com.atlassian.jira.web.filters.PathMatchingEncodingFilter.doFilter(PathMatchingEncodingFilter.java:41)
jira-srv | 		at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.jira.web.filters.MultipartBoundaryCheckFilter.doFilter(MultipartBoundaryCheckFilter.java:36)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.jira.servermetrics.MetricsCollectorFilter.doFilter(MetricsCollectorFilter.java:25)
jira-srv | 		at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.jira.web.filters.steps.ChainedFilterStepRunner.doFilter(ChainedFilterStepRunner.java:74)
jira-srv | 		at com.atlassian.jira.web.filters.JiraFirstFilter.doFilter(JiraFirstFilter.java:57)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at com.atlassian.gzipfilter.GzipFilter.doFilterInternal(GzipFilter.java:115)
jira-srv | 		at com.atlassian.gzipfilter.GzipFilter.doFilter(GzipFilter.java:92)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
jira-srv | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
jira-srv | 		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
jira-srv | 		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
jira-srv | 		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
jira-srv | 		at org.apache.catalina.valves.StuckThreadDetectionValve.invoke(StuckThreadDetectionValve.java:206)
jira-srv | 		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
jira-srv | 		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
jira-srv | 		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
jira-srv | 		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
jira-srv | 		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
jira-srv | 		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
jira-srv | 		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
jira-srv | 		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
jira-srv | 		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
jira-srv | 		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
jira-srv | 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jira-srv | 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jira-srv | 		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
jira-srv | 		at java.lang.Thread.run(Thread.java:748)

**Comment by haxqer** [comment]
Could you show your config with picture or text?

later, I will upload some tutorial picture to The Jira project.

**Comment by haxqer** [comment]
1. Could you show me more context ( configure or console info )?
2. Could you show me your host env ( CPU Memory Disk .ect )?
3. Please try haxqer/jira:8.3.1

**Comment by kiaxseventh** [comment]
dear @duudo  are you remember how did you fixed this problem ?
