### ISSUE TITLE
使用您这个版本丢失了部分功能，详见内容，感谢

### ISSUE THREAD

**Issue by yyf-ytt** [haxqer/jira#20]
比如：
系统设置里面- 》身份认证方式-》只有一个crowd认证模式，缺少了其他两项选择，《OpenID Connet 单点登陆》和saml登陆

**Comment by yyf-ytt** [comment]
@haxqer 求解答，感谢

**Comment by haxqer** [comment]
我猜测你没有用 https ....

The application base URL is not HTTPS
Due to security risks neither SAML nor OpenID Connect are allowed with an insecure connection. Please ensure that your server is using HTTPS and that your application base URL is configured appropriately.

**Comment by yyf-ytt** [comment]
@haxqer 我找到了问题所在了，原因是需要data center😂，去小黄鱼花了点r发现的问题。

**Comment by haxqer** [comment]
加个 参数 `-d` 就是 datacenter 模式
比如
```bash
docker exec jira-srv java -jar /var/agent/atlassian-agent.jar \
    -d \
    -p jira \
    -m Hello@world.com \
    -n Hello@world.com \
    -o your-org \
    -s you-server-id-xxxx
```

**Comment by Reallymine** [comment]
非常感谢！
