### ISSUE TITLE
jira image  rm and no rm ，what is diff

### ISSUE THREAD

**Issue by liminghua999** [haxqer/jira#3]
in your docker image tags 
I fund 2 image
one have rm 
and another no rm 
what diff between them?

**Comment by haxqer** [comment]
"rm" branch is cracked jira

**Comment by nestaguo** [comment]
I installed jira via your docker-compose.yml(image: jira:rm). when I set my license in jira, i get a error message that is "This license is invalid. Please double-check that you have entered it correctly, and contact Support if the issue continues.". How do i solve it? 
Many Thanks

**Comment by haxqer** [comment]
- Please note your Server ID, and replace it.

- Please note your Production. If you need to crack `jira`(not plugins) , you should replace the parameters `-p jira`

.eg, my Server ID is : `BAEA-62PV-T41C-QL4J`

> docker exec jira-srv java -jar /var/agent/atlassian-agent.jar \
    -p jira \
    -m youremail@gmail.com \
    -n youremail@gmail.com \
    -o http://website \
    -s BAEA-62PV-T41C-QL4J

**Comment by nestaguo** [comment]
> 
> 
>     * Please note your Server ID, and replace it.
> 
>     * Please note your Production. If you need to crack `jira`(not plugins) , you should replace the parameters `-p jira`
> 
> 
> .eg, my Server ID is : `BAEA-62PV-T41C-QL4J`
> 
> > docker exec jira-srv java -jar /var/agent/atlassian-agent.jar 
> >     -p jira 
> >     -m [youremail@gmail.com](mailto:youremail@gmail.com) 
> >     -n [youremail@gmail.com](mailto:youremail@gmail.com) 
> >     -o http://website 
> >     -s BAEA-62PV-T41C-QL4J

Thanks for your relpy, I'll try again. Maybe I don't import .jar.
