### ISSUE TITLE
the mysql version is different with the mysql driver in jira image

### ISSUE THREAD

**Issue by LANB0-AI** [haxqer/jira#36]
In jira-srv image ,the mysql driver version is 8.0.22,but the mysql:8 image has been set to 8.1.0.
This will make error when configure the database connect info.

**Comment by JocelynFloresz** [comment]
I use mysql:8.0.34. everything works fine

**Comment by haxqer** [comment]
<img width="857" alt="image" src="https://github.com/haxqer/jira/assets/25882796/73b38c70-3bc1-4284-85b2-a3ba6b643970">
For the compatibility of the script, I have to use version 8.0.22. Here is the reference documentation：
https://confluence.atlassian.com/conf719/database-jdbc-drivers-1157467546.html

**Comment by haxqer** [comment]
I will later change `mysql:8` to `mysql:8.0`, thank you for your reminding.

**Comment by LANB0-AI** [comment]
> I use mysql:8.0.34. everything works fine

Maybe 8.0.x' driver works well with the 8.0.x's mysql.

**Comment by LANB0-AI** [comment]
> I will later change `mysql:8` to `mysql:8.0`, thank you for your reminding.

Thanks a lot,I also tried confluence image, same issue.

**Comment by haxqer** [comment]
Done~
If there are any further questions, thank you for your correction.

**Comment by haxqer** [comment]
The LTS version of Confluence supports 8.0.33, so I updated the mysql-driver to 8.0.33.
