### ISSUE TITLE
修改映射目录到主机后，web打开时报/var/jira权限问题

### ISSUE THREAD

**Issue by lasonlixin** [haxqer/jira#41]
如果不修改compose文件就是正常的，容器内部/var/jira是属主是root:root，请问有解决办法吗

**Comment by haxqer** [comment]
最简单粗暴的办法, chmod -R 777 宿主机的目录

查看容器内的 用户(id)对应在宿主机内的id，在宿主机里面给这个用户id针对这个目录的读写权限即可
