### ISSUE TITLE
无法激活 Jira Core

### ISSUE THREAD

**Issue by lovese** [haxqer/jira#46]
Jira Service Management 和 Jira Software 都成功激活了，但是 Jira Core 死活激活不了，是版本的问题吗？强迫症犯了🤭

![image](https://github.com/haxqer/jira/assets/13268438/47b631ef-0e44-46ad-8e04-5062fd282fc1)

哪位大哥知道要怎么激活？

**Comment by davoodkhany** [comment]
Hello, I also faced this problem, I could not activate jira core, does anyone have a solution?

**Comment by ithelpdeskBMBS** [comment]
> Jira Service Management 和 Jira Software 都成功激活了，但是 Jira Core 死活激活不了，是版本的问题吗？强迫症犯了🤭
> 
> ![image](https://private-user-images.githubusercontent.com/13268438/289806684-47b631ef-0e44-46ad-8e04-5062fd282fc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzQ0NzAsIm5iZiI6MTcwMzQ3NDE3MCwicGF0aCI6Ii8xMzI2ODQzOC8yODk4MDY2ODQtNDdiNjMxZWYtMGU0NC00NmFkLThlMDQtNTA2MmZkMjgyZmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDAzMTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZmU3ZGMwZjZmOTQxYWFhODY2NmJkZTc0MzJiZTFmM2MyYTRhOWJjZWVhODhjMGFjMjI0OGI2YzFmYmExNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PXgETYjYlcgt-ry8GzSIB3Zfk32UHwGD4MgfpNrFkWI)
> 
> 哪位大哥知道要怎么激活？

When you activate jira software products, jira core no longer makes sense, because jira core is a part of jira software.

**Comment by lovese** [comment]
> > Jira Service Management 和 Jira Software 都成功激活了，但是 Jira Core 死活激活不了，是版本的问题吗？强迫症犯了🤭
> > ![image](https://private-user-images.githubusercontent.com/13268438/289806684-47b631ef-0e44-46ad-8e04-5062fd282fc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzQ0NzAsIm5iZiI6MTcwMzQ3NDE3MCwicGF0aCI6Ii8xMzI2ODQzOC8yODk4MDY2ODQtNDdiNjMxZWYtMGU0NC00NmFkLThlMDQtNTA2MmZkMjgyZmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDAzMTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZmU3ZGMwZjZmOTQxYWFhODY2NmJkZTc0MzJiZTFmM2MyYTRhOWJjZWVhODhjMGFjMjI0OGI2YzFmYmExNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PXgETYjYlcgt-ry8GzSIB3Zfk32UHwGD4MgfpNrFkWI)
> > 哪位大哥知道要怎么激活？
> 
> When you activate jira software products, jira core no longer makes sense, because jira core is a part of jira software.

明白了，谢谢您！

**Comment by davoodkhany** [comment]
OH MY GOAD. THANKS
