### ISSUE TITLE
jira和confluence内存使用量限制为多少比较合适？

### ISSUE THREAD

**Issue by pygyme** [haxqer/jira#52]
我有一个Linux虚拟机，使用这边的dockerfile，在上面部署 jira 、confluence，以及它们依赖的数据库 mysql 8.0，就这三个应用，没有其他的了。

但是，让我很困惑的是：
+ 当我设置虚拟机的内存为 6G 的时候， 开启虚拟机后，应用会吃满内存。
+ 当我设置虚拟机的内存为 12G 的时候， 开启虚拟机后，应用也会吃满内存。
+ 当我设置虚拟机的内存为 16G 的时候， 开启虚拟机后，应用还是会吃掉 90% 以上的内存。

因为没什么访问量，按理来说，不应该吃掉这么多内存。

我查找了issue， [ 怎么调整内存呢？ #22 ](https://github.com/haxqer/jira/issues/22)，发现可以手动限制内存大小。

在应用能流畅使用的前提下， jira和confluence内存使用量限制为多少比较合适？

**Comment by haxqer** [comment]
https://github.com/haxqer/confluence/issues/47

**Comment by pygyme** [comment]
> confluence: [haxqer/confluence#47](https://github.com/haxqer/confluence/issues/47) jira: https://confluence.atlassian.com/jirakb/jira-server-sizing-guide-975033809.html

非常感谢你的回复， 我明白了。
