### ISSUE TITLE
mac m1 一直卡在载入这里，我数据库已经设置了

### ISSUE THREAD

**Issue by Xuzan9396** [haxqer/jira#55]
<img width="1194" alt="image" src="https://github.com/haxqer/jira/assets/24741439/53477097-2f2c-4c62-a39a-4169fe7b8bf2">

**Comment by haxqer** [comment]
1. 使用 [arm 架构的镜像](https://github.com/haxqer/jira/tree/rm/lts_arm)
2. 检查机器内存是否充足，尽量在服务器上运行。[jira server 对机器配置有要求](https://confluence.atlassian.com/adminjiraserver/jira-applications-installation-requirements-938846826.html#Jiraapplicationsinstallationrequirements-Server-siderequirementsforevaluationpurposes)
3. 检查存储
4. 查看报错日志，把日志贴出来看一下
