### ISSUE TITLE
https

### ISSUE THREAD

**Issue by kinkcamp** [haxqer/jira#67]
Hello haxqer, if I need to enable https, what parameters should I add to enable https protocol quickly?

**Comment by haxqer** [comment]
Method 1:
Nginx + TLS certificate + Modify one line of Jira configuration (domain)

Method 2:
https://github.com/haxqer/jira/blob/build-your-own/docker/.env.dist

Method 3, what I personally use:
A highly automated solution with automatic HTTPS setup: Traefik + Cloudflare (DNS API token).

**Comment by kinkcamp** [comment]
Thank you. The MySQL jar package in the newly submitted docker images is 5.7, and a jar error will be reported after deployment.
