### ISSUE TITLE
邮件邀请用户注册不生效

### ISSUE THREAD

**Issue by Fengqiv** [haxqer/jira#69]
Version: v9.12.10
配置了邮箱服务，测试可以正常发送邮件，但使用 {邮件邀请用户注册} 功能，用户收不到邮件

**Comment by haxqer** [comment]
通用的解决思路：
有系统日志的，可以查系统日志，看看有啥报错

“用户收不到邮件”:
检查用户的 “垃圾邮箱”，可能在垃圾邮箱里面

**Comment by Fengqiv** [comment]
pod的日志看了，只有在测试邮件时会有一条debug日志，但像ticket的创建修改，用户的修改密码等等需要发送邮件的地方都没有反应，jira系统设置中的邮件队列一直是0，也没看到任何日志

**Comment by haxqer** [comment]
检查邮件服务器设置：
+ 确认Jira中配置的邮件服务器设置是否正确，包括SMTP服务器地址、端口、用户名、密码以及SSL/TLS设置。
+ 检查邮件服务器的认证方式是否正确。

检查邮件模板：
+ 确认Jira中用于发送邮件的模板是否存在且配置正确，包括邮件的标题和内容。
+ 查看是否有特定的邮件模板被禁用或未配置。

检查事件触发器：
+ 确认在Jira中是否配置了正确的事件来触发邮件发送。
+ 检查是否有任何插件或自定义脚本可能影响了邮件发送的流程。
