### ISSUE TITLE
Jira 10.0.0 comes 

### ISSUE THREAD

**Issue by d1m0nstr** [haxqer/jira#77]
what do you think about it?

**Comment by haxqer** [comment]
Thank you for your suggestion, I have generated a docker image for Jira v10.0.0: 
https://github.com/haxqer/jira/blob/rm/beta/docker-compose.yml

**Comment by d1m0nstr** [comment]
Tnx - I've been testing the new system for the past two days. So far, 80% of the applications are still not working. I believe jira will be possible to update in a week or two.

**Comment by haxqer** [comment]
Cool
