### ISSUE TITLE
Status page for jira service management 

### ISSUE THREAD

**Issue by vexsx** [haxqer/jira#80]
Hi, I installed Jira Software version 9.12.12 followed by Service Management version 5.12.12. However, when I go to "Manage Apps" and try to find Statuspage, it's not available. I manually installed it, but it's showing as incompatible. Any suggestions on how to fix this?

**Comment by vexsx** [comment]
oh , thanks

**Comment by vexsx** [comment]
i will check it .

**Comment by voarsh2** [comment]
> If you need a reliable statuspage that can easily be integrated with Jira or other services, try Apache HertzBeat https://github.com/apache/hertzbeat

Not sure how it can be easily integrated with Jira - REST API? Or something?
