### ISSUE TITLE
rm-8.17.1 无法配置数据库

### ISSUE THREAD

**Issue by xukaisjz** [haxqer/jira#9]
在配置向导中一直无法通过数据库配置，后台提示设置useSSL=false，但是初次配置没有生成dbconfig.xml文件无法修改ssl配置

**Comment by haxqer** [comment]
刚测试了，你描述的问题没有复现。
dockerhub 中的`rm` tag 等同于 rm-7.18.1

---
我使用的方式是 `docker-compose up -d`
启动后访问 `http://YOUR_IP:8080`
选择 I'll set it up myself
然后 My Own Database

<img width="1642" alt="WeChat8706100631a9cccdf935f72e5aeb443a" src="https://user-images.githubusercontent.com/25882796/155441192-88224cd8-c2e3-4ffa-9d5c-b0774739ebd6.png">


---

能提供更详细的信息吗

**Comment by xukaisjz** [comment]
![image](https://user-images.githubusercontent.com/68056796/155445074-ed2a3fa1-2545-4fce-8661-0504278ad39a.png)

`Thu Feb 24 10:06:58 CST 2022 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.` 
以上是错误连接数据的截图和后台日期
另外我想问一下docker-compose方式的是不是连同mysql一同创建了，我想使用本地已有的数据库，rm tag的镜像我也试了也是同样的问题，是否对mysql小版本号或者配置有什么要求

**Comment by haxqer** [comment]
docker-compose 会同时创建 jira 和 mysql
mysql 的版本号我用的是 5.7， pull 的时候是 5.7 的最新版
---
晚点，我折腾一台腾讯的 db 试试

**Comment by haxqer** [comment]
---

目前测试下来，应该是 腾讯云的mysql开启了 ssl 验证

我本地数据库也没有问题，也用 docker启动的mysql 试过了
`docker run --name mysql-3308 -p 3308:3306 -e MYSQL_ROOT_PASSWORD=123123 -e MYSQL_DATABASE=jira -e MYSQL_USER=jira -e MYSQL_PASSWORD=123123 -d mysql:5.7 --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
`

---
不忙的时候，我给你看看怎么配 腾讯云的mysql，或者怎么方便的修改 jira 的配置文件

**Comment by suzhoutest** [comment]
我使用这个仓库的docker-compose.yml启动。出现提示mysql服务提示如下：
mysql-jira | mysql: [ERROR] unknown variable 'character-set-server=utf8mb4'

**Comment by haxqer** [comment]
可以看下你的 docker docker-compose 版本吗？

---

这里是录制的演示视频:
[![asciicast](https://asciinema.org/a/og69ftAndw6EQc1k8fCDMoMtn.svg)](https://asciinema.org/a/og69ftAndw6EQc1k8fCDMoMtn)

**Comment by xukaisjz** [comment]
不好意思忘了说了，问题解决了，通过容器中的config,sh来创建db文件，然后修改dbconfig.xml中的配置，重启容器就可以了
另外你问的compose版本，我是没有用compose方式安装，我从dockerhub上下载的具体版本镜像安装的

**Comment by suzhoutest** [comment]
@haxqer 十分抱歉，找到原因了。因为不是用git clone拉的yml文件(手动CV拷贝到终端的)。然后由于终端传输出了点问题，mysqld变成了mysql。接着命令很合理判定命令错误了。

**Comment by xukaisjz** [comment]
@haxqer 
![image](https://user-images.githubusercontent.com/68056796/155821725-ba257b11-3099-4ab5-9ff0-e9e6c63f8d78.png)

从哪里可以看到appkey呢？ 我再安装confluence的时候需要安装team calendar 和 questions 插件

**Comment by haxqer** [comment]
@suzhoutest 客气了

**Comment by xukaisjz** [comment]
@haxqer 请教一下roadmap怎么汉化 
![image](https://user-images.githubusercontent.com/68056796/156538947-00dc803b-6c01-4d31-bcf4-634d7e4068d8.png)

**Comment by haxqer** [comment]
@xukaisjz 
我没有用过汉化包，所以一下仅供参考，望谅解。
我大概知道有中文的 patch / plugin 翻译了一些常用的插件，你在 Marketplace 搜索 chinese 。
具体的，可能要你自己尝试了。
加油
